imports:
    - php

filter:
    excluded_paths:
        - vendor/*
        - storage/*
        - build/*
        - cache/*

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
